# The URL the site will be built for
base_url = "https://blog.uvvu.pw"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

theme = "after-dark"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
# Put all your custom variables here
after_dark_title = "UvvU Blog."
after_dark_menu = [
  { url = "$BASE_URL", name = "Home" },
  { url = "https://github.com/u-v-v-u", name = "Github" },
  { url = "$BASE_URL/categories", name = "Categories" },
  { url = "$BASE_URL/tags", name = "Tags" },
]
